language: bash

before_script:
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx -C test

script:
    - bash test/shell-util/decorate.sh
    - bash test/shell-util/properties.sh
    - bash test/opt-admin/application.sh
