language: bash

before_script:
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx -C test

branches:
    except:
        - feature/WIP_.*

script:
    - bash test/script/shell-util/log.sh
    - bash test/script/shell-util/sourcing.sh
    - bash test/script/shell-util/decorate.sh
    - bash test/script/shell-util/properties.sh
    - bash test/script/opt-admin/application.sh
    - bash test/script/config-util/variable.sh
    - bash test/script/config-util/read.sh
    - bash test/script/init-home/xdg.sh
    - bash test/script/init-home/bin_dir.sh
    - bash test/script/completion-helper/capacity.sh
