language: bash

sudo: required

jdk:
  - oraclejdk8

gradle:
  - oraclejdk8

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y sharutils git gawk
before_script:
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx -C test

branches:
    except:
        - feature/WIP_.*


deploy:
    provider: releases
    api_key:
        secure: "j9a5pkcDfVry1Zs4NW2/pe4s+O3nq4OV2kbeu2UuZjhvy4UQHptA8xCsYcrsQokhH78uLUhMS2LaUzoJnZFQiz6c9XhZr6q6Cd7LZ8tTt2dsw8lxdd1CqrpgaDL+4QKUO8YNxVvqJ0YHkL3nRA6bkYcEyeTOHSXz+2aytuJ6vaJuzZaCE1GaWg9g/3d8TiMnZPcCBPVkuaCvxnmyTueyTUJOXd99MeHjQy2XiRZvHvfBi4D9DXUgRQ4mZwqil3h1V9Viv94pwQV0VtulcU7pTn5cRGhS+uHcDv5UXbQ7buWbDdPtruLYfURHjau82klrTDobCsw92cQ+/BtLEm6/NeabGDDOghf/qC9p2WTJC1KMu7+2gW2LPOKe7LM1izu45uHFkw64KfYRole1LlDy9NWnY2de05SxcjlfruglBmiUK818/05bG3LNqkogbAf0BrVZr7o5/LAcDF+wBBxDzb5xiWQLiN5vlcE//Xlv3zEaVetSGsEce1hx8zqdiGJuuNv9NY34ZLIDHElUzYX1UcKY6ZgYWO90Tor9WiZr992rBwxKgc0uECJIJXx+4gIhkjUeZSvtC7T2X0Ug/CEFx3pyhRlWqA2oVkfsBKondd30vN+qjDKKDvIhDWKzyphYPGesODYadfcmBtxMFB+WdTd4U0d45sLA51CeUFIjUcQ="
    file_glob: true
    file: output/distrib/final*
    skip_cleanup: true
    on:
        tags: true

script:
    - bash test/script/shell-util/log.sh
    - bash test/script/shell-util/sourcing.sh
    - bash test/script/shell-util/decorate.sh
    - bash test/script/shell-util/properties.sh
    - bash test/script/config-util/variable.sh
    - bash test/script/config-util/read.sh
    - bash test/script/completion-helper/capacity.sh
    - bash test/script/opt-admin/application.sh
    - bash test/script/init-home/xdg.sh
    - bash test/script/init-home/bin_dir.sh
    - bash test/script/encode/encode.sh
    - bash test/script/timeout/timeout.sh
    - ./gradlew archiveZip selfExtractingArchive
